EXTRA_CFLAGS  := 
CFLAGS_file.o := 

obj-y += auto_page.o
obj-y += browse_page.o
obj-y += novel_page.o
obj-y += interval_page.o
obj-y += main_page.o
obj-y += page_manager.o
obj-y += setting_page.o
obj-y += manual_page.o
